config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  # get 'restaurants/index'

  # get 'restaurants/show'

  # get 'restaurants/new'

  # get 'restaurants/create'

  # get 'restaurants/edit'

  # get 'restaurants/update'

  # get 'restaurants/destroy'

  resources :restaurants
  resources :articles
  resources :responses

  root to: 'restaurants#index'
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  
  def index
    @responses = Response.all
    @response = Response.new
  end
 
  def show
  @response = Response.find(params[:id])
  end

  def new
    @response = Response.new
  end


  def edit
    @response = Response.find(params[:id])
  end

  def create
    @response = Response.new(response_params)
  
  if @response.save
    redirect_to @response
  else
    render 'new'
  end

   end

  def update
    @response = Response.find(params[:id])
 
    if @response.update(response_params)
      redirect_to @response
    else
      render 'edit'
    end
  end

  def destroy
  @response = Response.find(params[:id])
  @response.destroy

  redirect_to response_path
  end

 private
 
  def response_params
    params.require(:response).permit(:customer_name, :customer_email, :website, :opt_in, :review_quality)
  end

end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= form_for @response do |f| %>
 
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@response.errors.count, "error") %> prohibited
        this response from being saved:
      </h2>
      <ul>
        <% @response.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </p>
 
  <p>
    <%= f.label :customer_email %><br>
    <%= f.text_area :customer_email %>
  </p>

  <p>
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </p>

  <p>
    <%= f.label :opt_in %><br>
    <%= f.text_area :opt_in %>
  </p>

  <p>
    <%= f.label :review_quality %><br>
    <%= f.text_area :review_quality %>
  </p>

  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/responses/create.html.erb
<h1>Responses#create</h1>
<p>Find me in app/views/responses/create.html.erb</p>

app/views/responses/edit.html.erb
<h1>Edit Response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<div class="center jumbotron">
<h1>Welcome to the ReplyCoPilot</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th colspan="2"></th>
  </tr>
 
  <% @responses.each do |response| %>
    <tr>
      <td><%= response.customer_name %></td>
      <td><%= response.customer_email %></td>
      <td><%= response.website %></td>
      <td><%= response.opt_in %></td>
      <td><%= response.review_quality %></td>
      <td><%= link_to 'Show', response_path(response) %></td>
      <td><%= link_to 'New', new_response_path(response) %></td>
      <td><%= link_to 'Edit', edit_response_path(response) %></td>
      <td><%= link_to 'Destroy', response_path(response),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<h1>Responses#show</h1>

<p>
  <strong>Customer Name</strong>
  <%= @response.customer_name %>
</p>
 
<p>
  <strong>Customer Email</strong>
  <%= @response.customer_email %>
</p>

<p>
  <strong>Website</strong>
  <%= @response.website %>
</p>

<p>
  <strong>Opt In?</strong>
  <%= @response.opt_in %>
</p>

<p>
  <strong>Review Quality</strong>
  <%= @response.review_quality %>
</p>

<p><br>

<% if @response.review_quality == "positive" %>
    <% if @response.website == "twitter" %>
        <%= @response.twitter_positive %>
    <% elsif @response.website == "trip advisor" %>
        <%= @response.ta_positive %>
    <% else %>
        <%= @response.fyg_positive %>
    <% end %>
<% elsif @response.review_quality == "neutral" %>
    <% if @response.website == "twitter" %>
        <%= @response.twitter_neutral %>
    <% elsif @response.website == "trip advisor" %>
        <%= @response.ta_neutral %>
    <% else %>
        <%= @response.fyg_neutral %>
    <% end %>
<% elsif @response.review_quality == "negative" %>
    <% if @response.website == "twitter" %>
        <%= @response.twitter_negative %>
    <% elsif @response.website == "trip advisor" %>
        <%= @response.ta_negative %>
    <% else %>
        <%= @response.fyg_negative %>
    <% end %>
<% end %>

</p>