config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  # get 'restaurants/index'

  # get 'restaurants/show'

  # get 'restaurants/new'

  # get 'restaurants/create'

  # get 'restaurants/edit'

  # get 'restaurants/update'

  # get 'restaurants/destroy'

  resources :restaurants
  resources :articles
  resources :responses

  root to: 'restaurants#index'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, presence: true
	validates :address, presence: true
	validates :description, presence: true
	validates :phone_number, presence: true
	belongs_to :owner
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_owner!, except:[:index, :show]	

  def index
  	@restaurants = Restaurant.all
  end
 
  def show
	@restaurant = Restaurant.find(params[:id])
  end

  def new
  	@restaurant = Restaurant.new
  end


  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  def create
  	@restaurant = current_owner.restaurants.new(restaurant_params)
 	
 	if @restaurant.save
 		redirect_to @restaurant
 	else
 		render 'new'
 	end

   end

  def update
    @restaurant = Restaurant.find(params[:id])
 
	  if @restaurant.update(restaurant_params)
	    redirect_to @restaurant
	  else
	    render 'edit'
	  end
  end

  def destroy
	@restaurant = Restaurant.find(params[:id])
	@restaurant.destroy

	redirect_to restaurants_path
  end

 private
 
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :description)
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
 
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@restaurant.errors.count, "error") %> prohibited
        this restaurant from being saved:
      </h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_area :phone_number %>
  </p>

  

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="center jumbotron">
<h1>Welcome to the Restaurant App</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th colspan="2"></th>
  </tr>
 
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.description %></td>
      <td><%= restaurant.phone_number %></td>
      <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
      <td><%= link_to 'New', new_restaurant_path(restaurant) %></td>
      <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
      <td><%= link_to 'Destroy', restaurant_path(restaurant),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
 
<p>
  <strong>description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Address</strong>
  <%= @restaurant.address %>
</p>

<p>
	<strong>Phone Number</strong>
	<%= @restaurant.phone_number %>
</p>



<div>
  <li><%= link_to 'Index', controller: "restaurants", action: "index" %></li>
	<li><%= link_to 'Edit', edit_restaurant_path %></li>
	<li><%= link_to 'Destroy', controller: "restaurants" %></li><br>
</div>

<img src="https://maps.googleapis.com/maps/api/staticmap?center=<%=@restaurant.address%>
&zoom=13
&size=400x400
&markers=color:blue%7Clabel:S%7C<%=@restaurant.address%>" >