config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  # get 'restaurants/index'

  # get 'restaurants/show'

  # get 'restaurants/new'

  # get 'restaurants/create'

  # get 'restaurants/edit'

  # get 'restaurants/update'

  # get 'restaurants/destroy'

  resources :restaurants
  resources :articles
  resources :responses

  root to: 'restaurants#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Restaurant App", restaurants_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          	<% if owner_signed_in? %>
          		<li><%= link_to current_owner.email, edit_owner_registration_path %></li>
          		<li><%= link_to "Logout", destroy_owner_session_path, method: :delete  %></li>
          	<% else %>
	            <li><%= link_to "Sign Up", new_owner_registration_path %></li>
	            <li><%= link_to "Login", new_owner_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <br>
    <div class="container">
		<% if notice %><div class="alert alert-info"><%= notice %> </div><% end %>
		<% if alert %><div class="alert alert-warning"><%= alert %> </div><% end %>
    	<%= yield %>
    </div>

</body>
</html>